<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>Shinoyami</Authors>
    <Version>1.0.0.2</Version>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <None Update="AutoRaiseAccept.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="README.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
